spring:
  application:
    name: data-manager
  cloud:
    nacos:
      discovery:
        server-addr: 18.142.67.104:8848 #Nacos服务注册中心地址

  # redis 配置
  redis:
    # 地址
    host: 18.142.67.104
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: AAK212@VS%
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://18.142.67.104:3306/sys-data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: AAK212@VS%
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
      validation-timeout: 1000
    dataNodes: sys-data.data_coins_2108,sys-data.data_coins_2109

shardingjdbc:
  sql:
    show: true
