spring:
  application:
    name: data-manager
  cloud:
    nacos:
      discovery:
        server-addr: 18.142.67.104:8848 #Nacos服务注册中心地址

  # redis 配置
  redis:
    # 地址
    host: 18.142.67.104
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: AAK212@VS%
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://18.142.67.104:3306/sys-data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: AAK212@VS%
    driver-class-name: com.mysql.cj.jdbc.Driver
    cardNodes: sys-data.data_card_2108,sys-data.data_card_2109,sys-data.data_card_2110

    coinsNodes: sys-data.data_coins_2108,sys-data.data_coins_2109,sys-data.data_coins_2110

    cardUserNodes: sys-data.data_card_user_2108,sys-data.data_card_user_2109,sys-data.data_card_user_2110

    sqlShow: true


global-config:
  #接口地址
  apiUrl: http://10.39.1.24:8030
  #错误日志上传地址
  errUploadUrl: http://13.228.208.170:6661/starry/logs/upload
  #头像下载地址
  headUrl: http://13.228.208.170:13003/upload
  #更新包下载地址
  resourcesUrl: http://18.142.67.104:8030
  #游戏配置
  gameConfig: { "lobby": -1,"update": -1,"psz": 1,"kpqz": 2,"ddz": 3,"ddz_laizi": 4,"hjk": 5,"fish": 6,"jzhw": 7,"ermj": 8,"shjx": 9,
               "hhdz": 2000,"brnn": 2001,"brnn_ten": 2002,"lhdz": 2003,"sgj": 2004,"bbd": 2005,"bjl": 2006,"ebg": 2007,"hbsl": 2008,"dzpk": 2009,
               "rummy": 2010,"teen_patti": 2011,"ghz": 2012,"wrzjh": 2014,"tb": 2015,"mssj": 2016,"jxqy": 2017,"jdqs": 2018,"hlxd": 2019,"bxjg": 2020,
               "pdsgj": 2021,"wzry": 2022 }
#  profile: D:/package/apk
  profile: /home/manager/package/apk
  #游戏服 地址
  domain: http://10.39.1.88:8888
  #发送游戏配置
  gameSend: /upload


