##多数据源
datasource:
  #主库
  master:
    jdbcUrl: jdbc:mysql://54.151.183.63:3306/sys-manager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ak-root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
  #从库
  slave:
    #并非url而是jdbcUrl(因为这个在获取数据源时一直报错，看了DataSource的属性才知道是jdbcUrl)
    jdbcUrl: jdbc:mysql://54.151.183.63:3306/sys-data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ak-root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20

##mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.job.executor.domain
  check-config-location: true
  config-location: classpath:mybatis-config.xml
