spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://18.142.67.104:3306/sys-data?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: AAK212@VS%
    driver-class-name: com.mysql.cj.jdbc.Driver
    cardNodes: sys-data.data_card_%s,sys-data.data_card_%s,sys-data.data_card_%s
    coinsNodes: sys-data.data_coins_%s,sys-data.data_coins_%s,sys-data.data_coins_%s
    cardUserNodes: sys-data.data_card_user_%s,sys-data.data_card_user_%s,sys-data.data_card_user_%s

    sqlShow: true
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.job.executor.domain
  check-config-location: true
  config-location: classpath:mybatis-config.xml

#接口地址
global-config:
  domain: http://18.142.67.104:8888
  onlinePlay: /get_play_info
