spring:
  datasource:
    url: jdbc:mysql://18.142.67.104:3306/sys-data?useUnicode=true&characterEncoding=utf-8
    username: root
    password: AAK212@VS%
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.job.executor.domain
  check-config-location: true
  config-location: classpath:mybatis-config.xml

#接口地址
global-config:
  domain: http://18.142.67.104:8888
  onlinePlay: /get_play_info
