# Spring环境配置
spring:
  profiles:
    active: dev
#    active: prod

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB

  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.manager.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
